ms-bodega:
  build:
    context: ./ms-bodega
    dockerfile: Dockerfile
  container_name: ms-bodega
  ports:
    - "8085:8085"
  environment:
    - SPRING_APPLICATION_NAME=ms-bodega
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    - JAVA_OPTS=-Xmx256m -Xms128m
    # ✅ Oracle con Wallet
    - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@mmg8hvewk688yrh4_low?TNS_ADMIN=/app/wallet
    - SPRING_DATASOURCE_USERNAME=SCHEMA_BODEGA
    - SPRING_DATASOURCE_PASSWORD=FullStack-Bodega1
    - SPRING_DATASOURCE_DRIVER_CLASS_NAME=oracle.jdbc.OracleDriver
    - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.OracleDialect
    - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    - TNS_ADMIN=/app/wallet
  depends_on:
    eureka-server:
      condition: service_healthy
  networks:
    - bodega-network
  restart: unless-stopped